#ifndef __Resources_H__
#define __Resources_H__


#define ANI_MUSHROOM_RUN "ANI_MUSHROOM_RUN"
#define FRA_MUSHROOM_DIE1 "FRA_MUSHROOM_DIE1"
#define FRA_MUSHROOM_DIE2 "FRA_MUSHROOM_DIE2"

#define ANI_TORTOISE_FLY_LEFT "ANI_TORTOISE_FLY_LEFT"
#define ANI_TORTOISE_RUN_LEFT "ANI_TORTOISE_RUN_LEFT"
#define ANI_TORTOISE_RUN_RIGHT "ANI_TORTOISE_RUN_RIGHT"
#define ANI_TORTOISE_FLY_RIGHT "ANI_TORTOISE_FLY_RIGHT"
#define ANI_TORTOISE_SCARED "ANI_TORTOISE_SCARED"

#define ANI_FLOWER "ANI_FLOWER"
#define FRA_MUSHROOM_REWARD1 "FRA_MUSHROOM_REWARD1"
#define FRA_MUSHROOM_REWARD2 "FRA_MUSHROOM_REWARD2"
#define FRA_MUSHROOM_REWARD3 "FRA_MUSHROOM_REWARD3"

#define FRA_FLAG "FRA_FLAG"

#define ANI_MARIO_WALK_LEFT_SML "ANI_MARIO_WALK_LEFT_SML"
#define ANI_MARIO_WALK_RIGHT_SML  "ANI_MARIO_WALK_RIGHT_SML"
#define ANI_MARIO_DIE_SML "ANI_MARIO_DIE_SML"
#define ANI_MARIO_WALK_LEFT_BIG "ANI_MARIO_WALK_LEFT_BIG"
#define ANI_MARIO_WALK_RIGHT_BIG "ANI_MARIO_WALK_RIGHT_BIG"

#define FRA_MARIO_JUMP_LEFT_SML "FRA_MARIO_JUMP_LEFT_SML"
#define FRA_MARIO_JUMP_RIGHT_SML "FRA_MARIO_JUMP_RIGHT_SML"
#define FRA_MARIO_JUMP_LEFT_BIG "FRA_MARIO_JUMP_LEFT_BIG"
#define FRA_MARIO_JUMP_RIGHT_BIG "FRA_MARIO_JUMP_RIGHT_BIG"

#define ANI_FLYFISH_LEFT "ANI_FLYFISH_LEFT"
#define ANI_FLYFISH_RIGHT "ANI_FLYFISH_RIGHT"

#define ANI_BOSS_LEFT "ANI_BOSS_LEFT"
#define ANI_BOSS_RIGHT "ANI_BOSS_RIGHT"
#define ANI_BOSS_BULLET_LEFT "ANI_BOSS_BULLET_LEFT"
#define ANI_BOSS_BULLET_RIGHT "ANI_BOSS_BULLET_RIGHT"

enum class ZOrder {MapNormal=1000, MushroomReward, MushroomAddLife, Block, Flower, Pipe, Flag,   RoleNormal};



#endif